version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant
    container_name: medi-link-qdrant
    ports:
      - "6333:6333" # The API port
      - "6334:6334" # The GRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always
